# version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  invent:
    build:
      context: .
      dockerfile: invent/DockerFile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:qwerty@db:5432/testdb
    depends_on:
      - db
    networks:
      - app-network

  history:
    build:
      context: .
      dockerfile: history/DockerFile
    ports:
      - "4000:4000"
      
    environment:
      DATABASE_URL: postgres://postgres:qwerty@db:5432/testdb
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
