# Используем официальный Node.js образ
FROM node:14

# Устанавливаем рабочую директорию
WORKDIR /usr/src/app

# Копируем файлы package.json и package-lock.json
COPY invent/package*.json ./ ./

# Устанавливаем зависимости
RUN npm install

# Копируем все остальные файлы
COPY invent/ ./

# Устанавливаем переменные окружения
ENV NODE_ENV=production
ENV DATABASE_URL=postgres://user:password@db:5432/database

# Открываем порт
EXPOSE 3000

# Запускаем приложение
CMD ["node", "index.js"]
